export const ChaiConfig = {
    // ==================== BACKGROUNDS ====================
    bg: {
        // Reds
        'red-50': { backgroundColor: '#fef2f2' },
        'red-100': { backgroundColor: '#fee2e2' },
        'red-200': { backgroundColor: '#fecaca' },
        'red-300': { backgroundColor: '#fca5a5' },
        'red-400': { backgroundColor: '#f87171' },
        'red-500': { backgroundColor: '#ef4444' },
        'red-600': { backgroundColor: '#dc2626' },
        'red-700': { backgroundColor: '#b91c1c' },
        'red-800': { backgroundColor: '#991b1b' },
        'red-900': { backgroundColor: '#7f1a1a' },
        'red-950': { backgroundColor: '#450a0a' },
        'red': { backgroundColor: '#ef4444' },
        
        // Oranges
        'orange-50': { backgroundColor: '#fff7ed' },
        'orange-100': { backgroundColor: '#ffedd5' },
        'orange-200': { backgroundColor: '#fed7aa' },
        'orange-300': { backgroundColor: '#fdba74' },
        'orange-400': { backgroundColor: '#fb923c' },
        'orange-500': { backgroundColor: '#f97316' },
        'orange-600': { backgroundColor: '#ea580c' },
        'orange-700': { backgroundColor: '#c2410c' },
        'orange-800': { backgroundColor: '#9a3412' },
        'orange-900': { backgroundColor: '#7c2d12' },
        'orange-950': { backgroundColor: '#431407' },
        'orange': { backgroundColor: '#f97316' },
        
        // Yellows
        'yellow-50': { backgroundColor: '#fefce8' },
        'yellow-100': { backgroundColor: '#fef9c3' },
        'yellow-200': { backgroundColor: '#fef08a' },
        'yellow-300': { backgroundColor: '#fde047' },
        'yellow-400': { backgroundColor: '#facc15' },
        'yellow-500': { backgroundColor: '#eab308' },
        'yellow-600': { backgroundColor: '#ca8a04' },
        'yellow-700': { backgroundColor: '#a16207' },
        'yellow-800': { backgroundColor: '#854d0e' },
        'yellow-900': { backgroundColor: '#713f12' },
        'yellow-950': { backgroundColor: '#422006' },
        'yellow': { backgroundColor: '#eab308' },
        
        // Greens
        'green-50': { backgroundColor: '#f0fdf4' },
        'green-100': { backgroundColor: '#dcfce7' },
        'green-200': { backgroundColor: '#bbf7d0' },
        'green-300': { backgroundColor: '#86efac' },
        'green-400': { backgroundColor: '#4ade80' },
        'green-500': { backgroundColor: '#22c55e' },
        'green-600': { backgroundColor: '#16a34a' },
        'green-700': { backgroundColor: '#15803d' },
        'green-800': { backgroundColor: '#166534' },
        'green-900': { backgroundColor: '#14532d' },
        'green-950': { backgroundColor: '#052e16' },
        'green': { backgroundColor: '#22c55e' },
        
        // Emeralds
        'emerald-50': { backgroundColor: '#ecfdf5' },
        'emerald-100': { backgroundColor: '#d1fae5' },
        'emerald-200': { backgroundColor: '#a7f3d0' },
        'emerald-300': { backgroundColor: '#6ee7b7' },
        'emerald-400': { backgroundColor: '#34d399' },
        'emerald-500': { backgroundColor: '#10b981' },
        'emerald-600': { backgroundColor: '#059669' },
        'emerald-700': { backgroundColor: '#047857' },
        'emerald-800': { backgroundColor: '#065f46' },
        'emerald-900': { backgroundColor: '#064e3b' },
        'emerald-950': { backgroundColor: '#022c22' },
        'emerald': { backgroundColor: '#10b981' },
        
        // Blues
        'blue-50': { backgroundColor: '#eff6ff' },
        'blue-100': { backgroundColor: '#dbeafe' },
        'blue-200': { backgroundColor: '#bfdbfe' },
        'blue-300': { backgroundColor: '#93c5fd' },
        'blue-400': { backgroundColor: '#60a5fa' },
        'blue-500': { backgroundColor: '#3b82f6' },
        'blue-600': { backgroundColor: '#2563eb' },
        'blue-700': { backgroundColor: '#1d4ed8' },
        'blue-800': { backgroundColor: '#1e40af' },
        'blue-900': { backgroundColor: '#1e3a8a' },
        'blue-950': { backgroundColor: '#172554' },
        'blue': { backgroundColor: '#3b82f6' },
        
        // Purples
        'purple-50': { backgroundColor: '#faf5ff' },
        'purple-100': { backgroundColor: '#f3e8ff' },
        'purple-200': { backgroundColor: '#e9d5ff' },
        'purple-300': { backgroundColor: '#d8b4fe' },
        'purple-400': { backgroundColor: '#c084fc' },
        'purple-500': { backgroundColor: '#a855f7' },
        'purple-600': { backgroundColor: '#9333ea' },
        'purple-700': { backgroundColor: '#7e22ce' },
        'purple-800': { backgroundColor: '#6b21a5' },
        'purple-900': { backgroundColor: '#581c87' },
        'purple-950': { backgroundColor: '#3b0764' },
        'purple': { backgroundColor: '#a855f7' },
        
        // Pinks
        'pink-50': { backgroundColor: '#fdf2f8' },
        'pink-100': { backgroundColor: '#fce7f3' },
        'pink-200': { backgroundColor: '#fbcfe8' },
        'pink-300': { backgroundColor: '#f9a8d4' },
        'pink-400': { backgroundColor: '#f472b6' },
        'pink-500': { backgroundColor: '#ec489a' },
        'pink-600': { backgroundColor: '#db2777' },
        'pink-700': { backgroundColor: '#be185d' },
        'pink-800': { backgroundColor: '#9d174d' },
        'pink-900': { backgroundColor: '#831843' },
        'pink-950': { backgroundColor: '#500724' },
        'pink': { backgroundColor: '#ec489a' },
        
        // Cyans
        'cyan-50': { backgroundColor: '#ecfeff' },
        'cyan-100': { backgroundColor: '#cffafe' },
        'cyan-200': { backgroundColor: '#a5f3fc' },
        'cyan-300': { backgroundColor: '#67e8f9' },
        'cyan-400': { backgroundColor: '#22d3ee' },
        'cyan-500': { backgroundColor: '#06b6d4' },
        'cyan-600': { backgroundColor: '#0891b2' },
        'cyan-700': { backgroundColor: '#0e7490' },
        'cyan-800': { backgroundColor: '#155e75' },
        'cyan-900': { backgroundColor: '#164e63' },
        'cyan-950': { backgroundColor: '#083344' },
        'cyan': { backgroundColor: '#06b6d4' },
        
        // Teals
        'teal-50': { backgroundColor: '#f0fdfa' },
        'teal-100': { backgroundColor: '#ccfbf1' },
        'teal-200': { backgroundColor: '#99f6e4' },
        'teal-300': { backgroundColor: '#5eead4' },
        'teal-400': { backgroundColor: '#2dd4bf' },
        'teal-500': { backgroundColor: '#14b8a6' },
        'teal-600': { backgroundColor: '#0d9488' },
        'teal-700': { backgroundColor: '#0f766e' },
        'teal-800': { backgroundColor: '#115e59' },
        'teal-900': { backgroundColor: '#134e4a' },
        'teal-950': { backgroundColor: '#042f2e' },
        'teal': { backgroundColor: '#14b8a6' },
        
        // Indigos
        'indigo-50': { backgroundColor: '#eef2ff' },
        'indigo-100': { backgroundColor: '#e0e7ff' },
        'indigo-200': { backgroundColor: '#c7d2fe' },
        'indigo-300': { backgroundColor: '#a5b4fc' },
        'indigo-400': { backgroundColor: '#818cf8' },
        'indigo-500': { backgroundColor: '#6366f1' },
        'indigo-600': { backgroundColor: '#4f46e5' },
        'indigo-700': { backgroundColor: '#4338ca' },
        'indigo-800': { backgroundColor: '#3730a3' },
        'indigo-900': { backgroundColor: '#312e81' },
        'indigo-950': { backgroundColor: '#1e1b4b' },
        'indigo': { backgroundColor: '#6366f1' },
        
        // Grays
        'gray-50': { backgroundColor: '#f9fafb' },
        'gray-100': { backgroundColor: '#f3f4f6' },
        'gray-200': { backgroundColor: '#e5e7eb' },
        'gray-300': { backgroundColor: '#d1d5db' },
        'gray-400': { backgroundColor: '#9ca3af' },
        'gray-500': { backgroundColor: '#6b7280' },
        'gray-600': { backgroundColor: '#4b5563' },
        'gray-700': { backgroundColor: '#374151' },
        'gray-800': { backgroundColor: '#1f2937' },
        'gray-900': { backgroundColor: '#111827' },
        'gray-950': { backgroundColor: '#030712' },
        
        // Zinc
        'zinc-50': { backgroundColor: '#fafafa' },
        'zinc-100': { backgroundColor: '#f4f4f5' },
        'zinc-200': { backgroundColor: '#e4e4e7' },
        'zinc-300': { backgroundColor: '#d4d4d8' },
        'zinc-400': { backgroundColor: '#a1a1aa' },
        'zinc-500': { backgroundColor: '#71717a' },
        'zinc-600': { backgroundColor: '#52525b' },
        'zinc-700': { backgroundColor: '#3f3f46' },
        'zinc-800': { backgroundColor: '#27272a' },
        'zinc-900': { backgroundColor: '#18181b' },
        'zinc-950': { backgroundColor: '#09090b' },
        
        // Neutral
        'neutral-50': { backgroundColor: '#fafafa' },
        'neutral-100': { backgroundColor: '#f5f5f5' },
        'neutral-200': { backgroundColor: '#e5e5e5' },
        'neutral-300': { backgroundColor: '#d4d4d4' },
        'neutral-400': { backgroundColor: '#a3a3a3' },
        'neutral-500': { backgroundColor: '#737373' },
        'neutral-600': { backgroundColor: '#525252' },
        'neutral-700': { backgroundColor: '#404040' },
        'neutral-800': { backgroundColor: '#262626' },
        'neutral-900': { backgroundColor: '#171717' },
        'neutral-950': { backgroundColor: '#0a0a0a' },
        
        // Stone
        'stone-50': { backgroundColor: '#fafaf9' },
        'stone-100': { backgroundColor: '#f5f5f4' },
        'stone-200': { backgroundColor: '#e7e5e4' },
        'stone-300': { backgroundColor: '#d6d3d1' },
        'stone-400': { backgroundColor: '#a8a29e' },
        'stone-500': { backgroundColor: '#78716c' },
        'stone-600': { backgroundColor: '#57534e' },
        'stone-700': { backgroundColor: '#44403c' },
        'stone-800': { backgroundColor: '#292524' },
        'stone-900': { backgroundColor: '#1c1917' },
        'stone-950': { backgroundColor: '#0c0a09' },
        
        // Basic colors
        'white': { backgroundColor: '#ffffff' },
        'black': { backgroundColor: '#000000' },
        'transparent': { backgroundColor: 'transparent' },
        'current': { backgroundColor: 'currentColor' }
    },

    // ==================== TEXT COLORS ====================
    text: {
        'white': { color: '#ffffff' },
        'black': { color: '#000000' },
        
        // Reds
        'red-50': { color: '#fef2f2' },
        'red-100': { color: '#fee2e2' },
        'red-200': { color: '#fecaca' },
        'red-300': { color: '#fca5a5' },
        'red-400': { color: '#f87171' },
        'red-500': { color: '#ef4444' },
        'red-600': { color: '#dc2626' },
        'red-700': { color: '#b91c1c' },
        'red-800': { color: '#991b1b' },
        'red-900': { color: '#7f1a1a' },
        'red-950': { color: '#450a0a' },
        'red': { color: '#ef4444' },
        
        // Oranges
        'orange-50': { color: '#fff7ed' },
        'orange-100': { color: '#ffedd5' },
        'orange-200': { color: '#fed7aa' },
        'orange-300': { color: '#fdba74' },
        'orange-400': { color: '#fb923c' },
        'orange-500': { color: '#f97316' },
        'orange-600': { color: '#ea580c' },
        'orange-700': { color: '#c2410c' },
        'orange-800': { color: '#9a3412' },
        'orange-900': { color: '#7c2d12' },
        'orange-950': { color: '#431407' },
        'orange': { color: '#f97316' },
        
        // Yellows
        'yellow-50': { color: '#fefce8' },
        'yellow-100': { color: '#fef9c3' },
        'yellow-200': { color: '#fef08a' },
        'yellow-300': { color: '#fde047' },
        'yellow-400': { color: '#facc15' },
        'yellow-500': { color: '#eab308' },
        'yellow-600': { color: '#ca8a04' },
        'yellow-700': { color: '#a16207' },
        'yellow-800': { color: '#854d0e' },
        'yellow-900': { color: '#713f12' },
        'yellow-950': { color: '#422006' },
        'yellow': { color: '#eab308' },
        
        // Greens
        'green-50': { color: '#f0fdf4' },
        'green-100': { color: '#dcfce7' },
        'green-200': { color: '#bbf7d0' },
        'green-300': { color: '#86efac' },
        'green-400': { color: '#4ade80' },
        'green-500': { color: '#22c55e' },
        'green-600': { color: '#16a34a' },
        'green-700': { color: '#15803d' },
        'green-800': { color: '#166534' },
        'green-900': { color: '#14532d' },
        'green-950': { color: '#052e16' },
        'green': { color: '#22c55e' },
        
        // Blues
        'blue-50': { color: '#eff6ff' },
        'blue-100': { color: '#dbeafe' },
        'blue-200': { color: '#bfdbfe' },
        'blue-300': { color: '#93c5fd' },
        'blue-400': { color: '#60a5fa' },
        'blue-500': { color: '#3b82f6' },
        'blue-600': { color: '#2563eb' },
        'blue-700': { color: '#1d4ed8' },
        'blue-800': { color: '#1e40af' },
        'blue-900': { color: '#1e3a8a' },
        'blue-950': { color: '#172554' },
        'blue': { color: '#3b82f6' },
        
        // Purples
        'purple-50': { color: '#faf5ff' },
        'purple-100': { color: '#f3e8ff' },
        'purple-200': { color: '#e9d5ff' },
        'purple-300': { color: '#d8b4fe' },
        'purple-400': { color: '#c084fc' },
        'purple-500': { color: '#a855f7' },
        'purple-600': { color: '#9333ea' },
        'purple-700': { color: '#7e22ce' },
        'purple-800': { color: '#6b21a5' },
        'purple-900': { color: '#581c87' },
        'purple-950': { color: '#3b0764' },
        'purple': { color: '#a855f7' },
        
        // Pinks
        'pink-50': { color: '#fdf2f8' },
        'pink-100': { color: '#fce7f3' },
        'pink-200': { color: '#fbcfe8' },
        'pink-300': { color: '#f9a8d4' },
        'pink-400': { color: '#f472b6' },
        'pink-500': { color: '#ec489a' },
        'pink-600': { color: '#db2777' },
        'pink-700': { color: '#be185d' },
        'pink-800': { color: '#9d174d' },
        'pink-900': { color: '#831843' },
        'pink-950': { color: '#500724' },
        'pink': { color: '#ec489a' },
        
        // Grays
        'gray-50': { color: '#f9fafb' },
        'gray-100': { color: '#f3f4f6' },
        'gray-200': { color: '#e5e7eb' },
        'gray-300': { color: '#d1d5db' },
        'gray-400': { color: '#9ca3af' },
        'gray-500': { color: '#6b7280' },
        'gray-600': { color: '#4b5563' },
        'gray-700': { color: '#374151' },
        'gray-800': { color: '#1f2937' },
        'gray-900': { color: '#111827' },
        'gray-950': { color: '#030712' },
        
        // Font Sizes (rem)
        'xs': { fontSize: '0.75rem' },
        'sm': { fontSize: '0.875rem' },
        'base': { fontSize: '1rem' },
        'lg': { fontSize: '1.125rem' },
        'xl': { fontSize: '1.25rem' },
        '2xl': { fontSize: '1.5rem' },
        '3xl': { fontSize: '1.875rem' },
        '4xl': { fontSize: '2.25rem' },
        '5xl': { fontSize: '3rem' },
        '6xl': { fontSize: '3.75rem' },
        '7xl': { fontSize: '4.5rem' },
        '8xl': { fontSize: '6rem' },
        '9xl': { fontSize: '8rem' },
        
        // Text Alignment
        'left': { textAlign: 'left' },
        'center': { textAlign: 'center' },
        'right': { textAlign: 'right' },
        'justify': { textAlign: 'justify' },
        
        // Text Decoration
        'underline': { textDecoration: 'underline' },
        'line-through': { textDecoration: 'line-through' },
        'no-underline': { textDecoration: 'none' },
        
        // Text Transform
        'uppercase': { textTransform: 'uppercase' },
        'lowercase': { textTransform: 'lowercase' },
        'capitalize': { textTransform: 'capitalize' },
        'normal-case': { textTransform: 'none' },
        
        // Text Overflow
        'truncate': { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
        'overflow-ellipsis': { textOverflow: 'ellipsis' },
        'overflow-clip': { textOverflow: 'clip' },
        
        // Word Break
        'break-normal': { wordBreak: 'normal', overflowWrap: 'normal' },
        'break-words': { wordBreak: 'break-word' },
        'break-all': { wordBreak: 'break-all' },
        
        // Line Height
        'leading-none': { lineHeight: '1' },
        'leading-tight': { lineHeight: '1.25' },
        'leading-snug': { lineHeight: '1.375' },
        'leading-normal': { lineHeight: '1.5' },
        'leading-relaxed': { lineHeight: '1.625' },
        'leading-loose': { lineHeight: '2' },
        'leading-3': { lineHeight: '.75rem' },
        'leading-4': { lineHeight: '1rem' },
        'leading-5': { lineHeight: '1.25rem' },
        'leading-6': { lineHeight: '1.5rem' },
        'leading-7': { lineHeight: '1.75rem' },
        'leading-8': { lineHeight: '2rem' },
        'leading-9': { lineHeight: '2.25rem' },
        'leading-10': { lineHeight: '2.5rem' },
        
        // Letter Spacing
        'tracking-tighter': { letterSpacing: '-0.05em' },
        'tracking-tight': { letterSpacing: '-0.025em' },
        'tracking-normal': { letterSpacing: '0' },
        'tracking-wide': { letterSpacing: '0.025em' },
        'tracking-wider': { letterSpacing: '0.05em' },
        'tracking-widest': { letterSpacing: '0.1em' },
        
        // Text Indent
        'indent-0': { textIndent: '0' },
        'indent-px': { textIndent: '1px' },
        'indent-0.5': { textIndent: '0.125rem' },
        'indent-1': { textIndent: '0.25rem' },
        'indent-2': { textIndent: '0.5rem' },
        'indent-3': { textIndent: '0.75rem' },
        'indent-4': { textIndent: '1rem' },
        'indent-5': { textIndent: '1.25rem' },
        'indent-6': { textIndent: '1.5rem' },
        'indent-8': { textIndent: '2rem' },
        'indent-10': { textIndent: '2.5rem' },
        
        // Vertical Alignment
        'align-baseline': { verticalAlign: 'baseline' },
        'align-top': { verticalAlign: 'top' },
        'align-middle': { verticalAlign: 'middle' },
        'align-bottom': { verticalAlign: 'bottom' },
        'align-text-top': { verticalAlign: 'text-top' },
        'align-text-bottom': { verticalAlign: 'text-bottom' },
        'align-sub': { verticalAlign: 'sub' },
        'align-super': { verticalAlign: 'super' }
    },

    // ==================== FONT WEIGHTS ====================
    font: {
        'thin': { fontWeight: '100' },
        'extralight': { fontWeight: '200' },
        'light': { fontWeight: '300' },
        'normal': { fontWeight: '400' },
        'medium': { fontWeight: '500' },
        'semibold': { fontWeight: '600' },
        'bold': { fontWeight: '700' },
        'extrabold': { fontWeight: '800' },
        'black': { fontWeight: '900' }
    },

    // ==================== SPACING - PADDING ====================
    p: {
        '0': { padding: '0' },
        'px': { padding: '1px' },
        '0.5': { padding: '2px' },
        '1': { padding: '4px' },
        '1.5': { padding: '6px' },
        '2': { padding: '8px' },
        '2.5': { padding: '10px' },
        '3': { padding: '12px' },
        '3.5': { padding: '14px' },
        '4': { padding: '16px' },
        '5': { padding: '20px' },
        '6': { padding: '24px' },
        '7': { padding: '28px' },
        '8': { padding: '32px' },
        '9': { padding: '36px' },
        '10': { padding: '40px' },
        '11': { padding: '44px' },
        '12': { padding: '48px' },
        '14': { padding: '56px' },
        '16': { padding: '64px' },
        '20': { padding: '80px' },
        '24': { padding: '96px' },
        '28': { padding: '112px' },
        '32': { padding: '128px' },
        '36': { padding: '144px' },
        '40': { padding: '160px' },
        '44': { padding: '176px' },
        '48': { padding: '192px' },
        '52': { padding: '208px' },
        '56': { padding: '224px' },
        '60': { padding: '240px' },
        '64': { padding: '256px' },
        '72': { padding: '288px' },
        '80': { padding: '320px' },
        '96': { padding: '384px' },
        
        // Directional
        'x-0': { paddingLeft: '0', paddingRight: '0' },
        'x-px': { paddingLeft: '1px', paddingRight: '1px' },
        'x-0.5': { paddingLeft: '2px', paddingRight: '2px' },
        'x-1': { paddingLeft: '4px', paddingRight: '4px' },
        'x-2': { paddingLeft: '8px', paddingRight: '8px' },
        'x-3': { paddingLeft: '12px', paddingRight: '12px' },
        'x-4': { paddingLeft: '16px', paddingRight: '16px' },
        'x-5': { paddingLeft: '20px', paddingRight: '20px' },
        'x-6': { paddingLeft: '24px', paddingRight: '24px' },
        'x-8': { paddingLeft: '32px', paddingRight: '32px' },
        'x-10': { paddingLeft: '40px', paddingRight: '40px' },
        'x-12': { paddingLeft: '48px', paddingRight: '48px' },
        'x-16': { paddingLeft: '64px', paddingRight: '64px' },
        'x-20': { paddingLeft: '80px', paddingRight: '80px' },
        'x-24': { paddingLeft: '96px', paddingRight: '96px' },
        
        'y-0': { paddingTop: '0', paddingBottom: '0' },
        'y-px': { paddingTop: '1px', paddingBottom: '1px' },
        'y-0.5': { paddingTop: '2px', paddingBottom: '2px' },
        'y-1': { paddingTop: '4px', paddingBottom: '4px' },
        'y-2': { paddingTop: '8px', paddingBottom: '8px' },
        'y-3': { paddingTop: '12px', paddingBottom: '12px' },
        'y-4': { paddingTop: '16px', paddingBottom: '16px' },
        'y-5': { paddingTop: '20px', paddingBottom: '20px' },
        'y-6': { paddingTop: '24px', paddingBottom: '24px' },
        'y-8': { paddingTop: '32px', paddingBottom: '32px' },
        'y-10': { paddingTop: '40px', paddingBottom: '40px' },
        'y-12': { paddingTop: '48px', paddingBottom: '48px' },
        'y-16': { paddingTop: '64px', paddingBottom: '64px' },
        'y-20': { paddingTop: '80px', paddingBottom: '80px' },
        'y-24': { paddingTop: '96px', paddingBottom: '96px' },
        
        't-0': { paddingTop: '0' },
        't-px': { paddingTop: '1px' },
        't-0.5': { paddingTop: '2px' },
        't-1': { paddingTop: '4px' },
        't-2': { paddingTop: '8px' },
        't-3': { paddingTop: '12px' },
        't-4': { paddingTop: '16px' },
        't-5': { paddingTop: '20px' },
        't-6': { paddingTop: '24px' },
        't-8': { paddingTop: '32px' },
        't-10': { paddingTop: '40px' },
        't-12': { paddingTop: '48px' },
        't-16': { paddingTop: '64px' },
        't-20': { paddingTop: '80px' },
        't-24': { paddingTop: '96px' },
        
        'r-0': { paddingRight: '0' },
        'r-px': { paddingRight: '1px' },
        'r-0.5': { paddingRight: '2px' },
        'r-1': { paddingRight: '4px' },
        'r-2': { paddingRight: '8px' },
        'r-3': { paddingRight: '12px' },
        'r-4': { paddingRight: '16px' },
        'r-5': { paddingRight: '20px' },
        'r-6': { paddingRight: '24px' },
        'r-8': { paddingRight: '32px' },
        'r-10': { paddingRight: '40px' },
        'r-12': { paddingRight: '48px' },
        'r-16': { paddingRight: '64px' },
        'r-20': { paddingRight: '80px' },
        'r-24': { paddingRight: '96px' },
        
        'b-0': { paddingBottom: '0' },
        'b-px': { paddingBottom: '1px' },
        'b-0.5': { paddingBottom: '2px' },
        'b-1': { paddingBottom: '4px' },
        'b-2': { paddingBottom: '8px' },
        'b-3': { paddingBottom: '12px' },
        'b-4': { paddingBottom: '16px' },
        'b-5': { paddingBottom: '20px' },
        'b-6': { paddingBottom: '24px' },
        'b-8': { paddingBottom: '32px' },
        'b-10': { paddingBottom: '40px' },
        'b-12': { paddingBottom: '48px' },
        'b-16': { paddingBottom: '64px' },
        'b-20': { paddingBottom: '80px' },
        'b-24': { paddingBottom: '96px' },
        
        'l-0': { paddingLeft: '0' },
        'l-px': { paddingLeft: '1px' },
        'l-0.5': { paddingLeft: '2px' },
        'l-1': { paddingLeft: '4px' },
        'l-2': { paddingLeft: '8px' },
        'l-3': { paddingLeft: '12px' },
        'l-4': { paddingLeft: '16px' },
        'l-5': { paddingLeft: '20px' },
        'l-6': { paddingLeft: '24px' },
        'l-8': { paddingLeft: '32px' },
        'l-10': { paddingLeft: '40px' },
        'l-12': { paddingLeft: '48px' },
        'l-16': { paddingLeft: '64px' },
        'l-20': { paddingLeft: '80px' },
        'l-24': { paddingLeft: '96px' }
    },

    // ==================== SPACING - MARGIN ====================
    m: {
        '0': { margin: '0' },
        'px': { margin: '1px' },
        '0.5': { margin: '2px' },
        '1': { margin: '4px' },
        '1.5': { margin: '6px' },
        '2': { margin: '8px' },
        '2.5': { margin: '10px' },
        '3': { margin: '12px' },
        '3.5': { margin: '14px' },
        '4': { margin: '16px' },
        '5': { margin: '20px' },
        '6': { margin: '24px' },
        '7': { margin: '28px' },
        '8': { margin: '32px' },
        '9': { margin: '36px' },
        '10': { margin: '40px' },
        '11': { margin: '44px' },
        '12': { margin: '48px' },
        '14': { margin: '56px' },
        '16': { margin: '64px' },
        '20': { margin: '80px' },
        '24': { margin: '96px' },
        '28': { margin: '112px' },
        '32': { margin: '128px' },
        '36': { margin: '144px' },
        '40': { margin: '160px' },
        '44': { margin: '176px' },
        '48': { margin: '192px' },
        '52': { margin: '208px' },
        '56': { margin: '224px' },
        '60': { margin: '240px' },
        '64': { margin: '256px' },
        '72': { margin: '288px' },
        '80': { margin: '320px' },
        '96': { margin: '384px' },
        'auto': { margin: 'auto' },
        
        // Directional
        'x-0': { marginLeft: '0', marginRight: '0' },
        'x-auto': { marginLeft: 'auto', marginRight: 'auto' },
        'x-px': { marginLeft: '1px', marginRight: '1px' },
        'x-0.5': { marginLeft: '2px', marginRight: '2px' },
        'x-1': { marginLeft: '4px', marginRight: '4px' },
        'x-2': { marginLeft: '8px', marginRight: '8px' },
        'x-3': { marginLeft: '12px', marginRight: '12px' },
        'x-4': { marginLeft: '16px', marginRight: '16px' },
        'x-5': { marginLeft: '20px', marginRight: '20px' },
        'x-6': { marginLeft: '24px', marginRight: '24px' },
        'x-8': { marginLeft: '32px', marginRight: '32px' },
        'x-10': { marginLeft: '40px', marginRight: '40px' },
        'x-12': { marginLeft: '48px', marginRight: '48px' },
        'x-16': { marginLeft: '64px', marginRight: '64px' },
        
        'y-0': { marginTop: '0', marginBottom: '0' },
        'y-auto': { marginTop: 'auto', marginBottom: 'auto' },
        'y-px': { marginTop: '1px', marginBottom: '1px' },
        'y-0.5': { marginTop: '2px', marginBottom: '2px' },
        'y-1': { marginTop: '4px', marginBottom: '4px' },
        'y-2': { marginTop: '8px', marginBottom: '8px' },
        'y-3': { marginTop: '12px', marginBottom: '12px' },
        'y-4': { marginTop: '16px', marginBottom: '16px' },
        'y-5': { marginTop: '20px', marginBottom: '20px' },
        'y-6': { marginTop: '24px', marginBottom: '24px' },
        'y-8': { marginTop: '32px', marginBottom: '32px' },
        'y-10': { marginTop: '40px', marginBottom: '40px' },
        'y-12': { marginTop: '48px', marginBottom: '48px' },
        'y-16': { marginTop: '64px', marginBottom: '64px' },
        
        't-0': { marginTop: '0' },
        't-auto': { marginTop: 'auto' },
        't-px': { marginTop: '1px' },
        't-0.5': { marginTop: '2px' },
        't-1': { marginTop: '4px' },
        't-2': { marginTop: '8px' },
        't-3': { marginTop: '12px' },
        't-4': { marginTop: '16px' },
        't-5': { marginTop: '20px' },
        't-6': { marginTop: '24px' },
        't-8': { marginTop: '32px' },
        't-10': { marginTop: '40px' },
        't-12': { marginTop: '48px' },
        't-16': { marginTop: '64px' },
        
        'r-0': { marginRight: '0' },
        'r-auto': { marginRight: 'auto' },
        'r-px': { marginRight: '1px' },
        'r-0.5': { marginRight: '2px' },
        'r-1': { marginRight: '4px' },
        'r-2': { marginRight: '8px' },
        'r-3': { marginRight: '12px' },
        'r-4': { marginRight: '16px' },
        'r-5': { marginRight: '20px' },
        'r-6': { marginRight: '24px' },
        'r-8': { marginRight: '32px' },
        'r-10': { marginRight: '40px' },
        'r-12': { marginRight: '48px' },
        'r-16': { marginRight: '64px' },
        
        'b-0': { marginBottom: '0' },
        'b-auto': { marginBottom: 'auto' },
        'b-px': { marginBottom: '1px' },
        'b-0.5': { marginBottom: '2px' },
        'b-1': { marginBottom: '4px' },
        'b-2': { marginBottom: '8px' },
        'b-3': { marginBottom: '12px' },
        'b-4': { marginBottom: '16px' },
        'b-5': { marginBottom: '20px' },
        'b-6': { marginBottom: '24px' },
        'b-8': { marginBottom: '32px' },
        'b-10': { marginBottom: '40px' },
        'b-12': { marginBottom: '48px' },
        'b-16': { marginBottom: '64px' },
        
        'l-0': { marginLeft: '0' },
        'l-auto': { marginLeft: 'auto' },
        'l-px': { marginLeft: '1px' },
        'l-0.5': { marginLeft: '2px' },
        'l-1': { marginLeft: '4px' },
        'l-2': { marginLeft: '8px' },
        'l-3': { marginLeft: '12px' },
        'l-4': { marginLeft: '16px' },
        'l-5': { marginLeft: '20px' },
        'l-6': { marginLeft: '24px' },
        'l-8': { marginLeft: '32px' },
        'l-10': { marginLeft: '40px' },
        'l-12': { marginLeft: '48px' },
        'l-16': { marginLeft: '64px' }
    },

    // ==================== BORDER RADIUS ====================
    rounded: {
        'none': { borderRadius: '0' },
        'sm': { borderRadius: '0.125rem' },
        'base': { borderRadius: '0.25rem' },
        'md': { borderRadius: '0.375rem' },
        'lg': { borderRadius: '0.5rem' },
        'xl': { borderRadius: '0.75rem' },
        '2xl': { borderRadius: '1rem' },
        '3xl': { borderRadius: '1.5rem' },
        '4xl': { borderRadius: '2rem' },
        'full': { borderRadius: '9999px' },
        
        // Individual corners
        't-sm': { borderTopLeftRadius: '0.125rem', borderTopRightRadius: '0.125rem' },
        't-md': { borderTopLeftRadius: '0.375rem', borderTopRightRadius: '0.375rem' },
        't-lg': { borderTopLeftRadius: '0.5rem', borderTopRightRadius: '0.5rem' },
        't-xl': { borderTopLeftRadius: '0.75rem', borderTopRightRadius: '0.75rem' },
        't-2xl': { borderTopLeftRadius: '1rem', borderTopRightRadius: '1rem' },
        't-full': { borderTopLeftRadius: '9999px', borderTopRightRadius: '9999px' },
        
        'b-sm': { borderBottomLeftRadius: '0.125rem', borderBottomRightRadius: '0.125rem' },
        'b-md': { borderBottomLeftRadius: '0.375rem', borderBottomRightRadius: '0.375rem' },
        'b-lg': { borderBottomLeftRadius: '0.5rem', borderBottomRightRadius: '0.5rem' },
        'b-xl': { borderBottomLeftRadius: '0.75rem', borderBottomRightRadius: '0.75rem' },
        'b-2xl': { borderBottomLeftRadius: '1rem', borderBottomRightRadius: '1rem' },
        'b-full': { borderBottomLeftRadius: '9999px', borderBottomRightRadius: '9999px' },
        
        'l-sm': { borderTopLeftRadius: '0.125rem', borderBottomLeftRadius: '0.125rem' },
        'l-md': { borderTopLeftRadius: '0.375rem', borderBottomLeftRadius: '0.375rem' },
        'l-lg': { borderTopLeftRadius: '0.5rem', borderBottomLeftRadius: '0.5rem' },
        'l-xl': { borderTopLeftRadius: '0.75rem', borderBottomLeftRadius: '0.75rem' },
        'l-2xl': { borderTopLeftRadius: '1rem', borderBottomLeftRadius: '1rem' },
        'l-full': { borderTopLeftRadius: '9999px', borderBottomLeftRadius: '9999px' },
        
        'r-sm': { borderTopRightRadius: '0.125rem', borderBottomRightRadius: '0.125rem' },
        'r-md': { borderTopRightRadius: '0.375rem', borderBottomRightRadius: '0.375rem' },
        'r-lg': { borderTopRightRadius: '0.5rem', borderBottomRightRadius: '0.5rem' },
        'r-xl': { borderTopRightRadius: '0.75rem', borderBottomRightRadius: '0.75rem' },
        'r-2xl': { borderTopRightRadius: '1rem', borderBottomRightRadius: '1rem' },
        'r-full': { borderTopRightRadius: '9999px', borderBottomRightRadius: '9999px' },
        
        'tl-sm': { borderTopLeftRadius: '0.125rem' },
        'tl-md': { borderTopLeftRadius: '0.375rem' },
        'tl-lg': { borderTopLeftRadius: '0.5rem' },
        'tl-xl': { borderTopLeftRadius: '0.75rem' },
        'tl-2xl': { borderTopLeftRadius: '1rem' },
        'tl-full': { borderTopLeftRadius: '9999px' },
        
        'tr-sm': { borderTopRightRadius: '0.125rem' },
        'tr-md': { borderTopRightRadius: '0.375rem' },
        'tr-lg': { borderTopRightRadius: '0.5rem' },
        'tr-xl': { borderTopRightRadius: '0.75rem' },
        'tr-2xl': { borderTopRightRadius: '1rem' },
        'tr-full': { borderTopRightRadius: '9999px' },
        
        'bl-sm': { borderBottomLeftRadius: '0.125rem' },
        'bl-md': { borderBottomLeftRadius: '0.375rem' },
        'bl-lg': { borderBottomLeftRadius: '0.5rem' },
        'bl-xl': { borderBottomLeftRadius: '0.75rem' },
        'bl-2xl': { borderBottomLeftRadius: '1rem' },
        'bl-full': { borderBottomLeftRadius: '9999px' },
        
        'br-sm': { borderBottomRightRadius: '0.125rem' },
        'br-md': { borderBottomRightRadius: '0.375rem' },
        'br-lg': { borderBottomRightRadius: '0.5rem' },
        'br-xl': { borderBottomRightRadius: '0.75rem' },
        'br-2xl': { borderBottomRightRadius: '1rem' },
        'br-full': { borderBottomRightRadius: '9999px' }
    },

    // ==================== BORDER WIDTH ====================
    border: {
        '0': { borderWidth: '0' },
        '': { borderWidth: '1px', borderStyle: 'solid' },
        '2': { borderWidth: '2px', borderStyle: 'solid' },
        '4': { borderWidth: '4px', borderStyle: 'solid' },
        '8': { borderWidth: '8px', borderStyle: 'solid' },
        
        't-0': { borderTopWidth: '0' },
        't': { borderTopWidth: '1px', borderTopStyle: 'solid' },
        't-2': { borderTopWidth: '2px', borderTopStyle: 'solid' },
        't-4': { borderTopWidth: '4px', borderTopStyle: 'solid' },
        't-8': { borderTopWidth: '8px', borderTopStyle: 'solid' },
        
        'r-0': { borderRightWidth: '0' },
        'r': { borderRightWidth: '1px', borderRightStyle: 'solid' },
        'r-2': { borderRightWidth: '2px', borderRightStyle: 'solid' },
        'r-4': { borderRightWidth: '4px', borderRightStyle: 'solid' },
        'r-8': { borderRightWidth: '8px', borderRightStyle: 'solid' },
        
        'b-0': { borderBottomWidth: '0' },
        'b': { borderBottomWidth: '1px', borderBottomStyle: 'solid' },
        'b-2': { borderBottomWidth: '2px', borderBottomStyle: 'solid' },
        'b-4': { borderBottomWidth: '4px', borderBottomStyle: 'solid' },
        'b-8': { borderBottomWidth: '8px', borderBottomStyle: 'solid' },
        
        'l-0': { borderLeftWidth: '0' },
        'l': { borderLeftWidth: '1px', borderLeftStyle: 'solid' },
        'l-2': { borderLeftWidth: '2px', borderLeftStyle: 'solid' },
        'l-4': { borderLeftWidth: '4px', borderLeftStyle: 'solid' },
        'l-8': { borderLeftWidth: '8px', borderLeftStyle: 'solid' },
        
        'solid': { borderStyle: 'solid' },
        'dashed': { borderStyle: 'dashed' },
        'dotted': { borderStyle: 'dotted' },
        'double': { borderStyle: 'double' },
        'none': { borderStyle: 'none' }
    },

    // ==================== BORDER COLOR ====================
    borderColor: {
        'transparent': { borderColor: 'transparent' },
        'current': { borderColor: 'currentColor' },
        'white': { borderColor: '#ffffff' },
        'black': { borderColor: '#000000' },
        
        'red-500': { borderColor: '#ef4444' },
        'orange-500': { borderColor: '#f97316' },
        'yellow-500': { borderColor: '#eab308' },
        'green-500': { borderColor: '#22c55e' },
        'blue-500': { borderColor: '#3b82f6' },
        'purple-500': { borderColor: '#a855f7' },
        'pink-500': { borderColor: '#ec489a' },
        'gray-500': { borderColor: '#6b7280' },
        'gray-700': { borderColor: '#374151' },
        'gray-800': { borderColor: '#1f2937' }
    },

    // ==================== FLEXBOX ====================
    flex: {
        '': { display: 'flex' },
        'inline': { display: 'inline-flex' },
        'col': { flexDirection: 'column' },
        'col-reverse': { flexDirection: 'column-reverse' },
        'row': { flexDirection: 'row' },
        'row-reverse': { flexDirection: 'row-reverse' },
        'wrap': { flexWrap: 'wrap' },
        'wrap-reverse': { flexWrap: 'wrap-reverse' },
        'nowrap': { flexWrap: 'nowrap' },
        'center': { justifyContent: 'center', alignItems: 'center' },
        'between': { justifyContent: 'space-between' },
        'around': { justifyContent: 'space-around' },
        'evenly': { justifyContent: 'space-evenly' },
        'start': { justifyContent: 'flex-start' },
        'end': { justifyContent: 'flex-end' },
        'items-start': { alignItems: 'flex-start' },
        'items-end': { alignItems: 'flex-end' },
        'items-center': { alignItems: 'center' },
        'items-baseline': { alignItems: 'baseline' },
        'items-stretch': { alignItems: 'stretch' },
        'self-start': { alignSelf: 'flex-start' },
        'self-end': { alignSelf: 'flex-end' },
        'self-center': { alignSelf: 'center' },
        'self-stretch': { alignSelf: 'stretch' },
        'grow': { flexGrow: '1' },
        'grow-0': { flexGrow: '0' },
        'shrink': { flexShrink: '1' },
        'shrink-0': { flexShrink: '0' }
    },

    // ==================== GRID ====================
    grid: {
        '': { display: 'grid' },
        'inline': { display: 'inline-grid' },
        'cols-1': { gridTemplateColumns: 'repeat(1, 1fr)' },
        'cols-2': { gridTemplateColumns: 'repeat(2, 1fr)' },
        'cols-3': { gridTemplateColumns: 'repeat(3, 1fr)' },
        'cols-4': { gridTemplateColumns: 'repeat(4, 1fr)' },
        'cols-5': { gridTemplateColumns: 'repeat(5, 1fr)' },
        'cols-6': { gridTemplateColumns: 'repeat(6, 1fr)' },
        'cols-7': { gridTemplateColumns: 'repeat(7, 1fr)' },
        'cols-8': { gridTemplateColumns: 'repeat(8, 1fr)' },
        'cols-9': { gridTemplateColumns: 'repeat(9, 1fr)' },
        'cols-10': { gridTemplateColumns: 'repeat(10, 1fr)' },
        'cols-11': { gridTemplateColumns: 'repeat(11, 1fr)' },
        'cols-12': { gridTemplateColumns: 'repeat(12, 1fr)' },
        
        'rows-1': { gridTemplateRows: 'repeat(1, 1fr)' },
        'rows-2': { gridTemplateRows: 'repeat(2, 1fr)' },
        'rows-3': { gridTemplateRows: 'repeat(3, 1fr)' },
        'rows-4': { gridTemplateRows: 'repeat(4, 1fr)' },
        'rows-5': { gridTemplateRows: 'repeat(5, 1fr)' },
        'rows-6': { gridTemplateRows: 'repeat(6, 1fr)' },
        
        'flow-row': { gridAutoFlow: 'row' },
        'flow-col': { gridAutoFlow: 'column' },
        'flow-dense': { gridAutoFlow: 'dense' },
        'flow-row-dense': { gridAutoFlow: 'row dense' },
        'flow-col-dense': { gridAutoFlow: 'column dense' }
    },

    // ==================== GAP ====================
    gap: {
        '0': { gap: '0' },
        '0.5': { gap: '2px' },
        '1': { gap: '4px' },
        '1.5': { gap: '6px' },
        '2': { gap: '8px' },
        '2.5': { gap: '10px' },
        '3': { gap: '12px' },
        '3.5': { gap: '14px' },
        '4': { gap: '16px' },
        '5': { gap: '20px' },
        '6': { gap: '24px' },
        '7': { gap: '28px' },
        '8': { gap: '32px' },
        '9': { gap: '36px' },
        '10': { gap: '40px' },
        '11': { gap: '44px' },
        '12': { gap: '48px' },
        '14': { gap: '56px' },
        '16': { gap: '64px' },
        '20': { gap: '80px' },
        '24': { gap: '96px' },
        
        'x-0': { columnGap: '0' },
        'x-0.5': { columnGap: '2px' },
        'x-1': { columnGap: '4px' },
        'x-2': { columnGap: '8px' },
        'x-3': { columnGap: '12px' },
        'x-4': { columnGap: '16px' },
        'x-5': { columnGap: '20px' },
        'x-6': { columnGap: '24px' },
        'x-8': { columnGap: '32px' },
        'x-10': { columnGap: '40px' },
        
        'y-0': { rowGap: '0' },
        'y-0.5': { rowGap: '2px' },
        'y-1': { rowGap: '4px' },
        'y-2': { rowGap: '8px' },
        'y-3': { rowGap: '12px' },
        'y-4': { rowGap: '16px' },
        'y-5': { rowGap: '20px' },
        'y-6': { rowGap: '24px' },
        'y-8': { rowGap: '32px' },
        'y-10': { rowGap: '40px' }
    },

    // ==================== OPACITY ====================
    opacity: {
        '0': { opacity: '0' },
        '5': { opacity: '0.05' },
        '10': { opacity: '0.1' },
        '15': { opacity: '0.15' },
        '20': { opacity: '0.2' },
        '25': { opacity: '0.25' },
        '30': { opacity: '0.3' },
        '35': { opacity: '0.35' },
        '40': { opacity: '0.4' },
        '45': { opacity: '0.45' },
        '50': { opacity: '0.5' },
        '55': { opacity: '0.55' },
        '60': { opacity: '0.6' },
        '65': { opacity: '0.65' },
        '70': { opacity: '0.7' },
        '75': { opacity: '0.75' },
        '80': { opacity: '0.8' },
        '85': { opacity: '0.85' },
        '90': { opacity: '0.9' },
        '95': { opacity: '0.95' },
        '100': { opacity: '1' }
    },

    // ==================== BOX SHADOW ====================
    shadow: {
        'sm': { boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)' },
        '': { boxShadow: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)' },
        'md': { boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)' },
        'lg': { boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)' },
        'xl': { boxShadow: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)' },
        '2xl': { boxShadow: '0 25px 50px -12px rgb(0 0 0 / 0.25)' },
        'inner': { boxShadow: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)' },
        'none': { boxShadow: 'none' }
    },

    // ==================== WIDTH ====================
    w: {
        '0': { width: '0' },
        'px': { width: '1px' },
        '0.5': { width: '2px' },
        '1': { width: '4px' },
        '1.5': { width: '6px' },
        '2': { width: '8px' },
        '2.5': { width: '10px' },
        '3': { width: '12px' },
        '3.5': { width: '14px' },
        '4': { width: '16px' },
        '5': { width: '20px' },
        '6': { width: '24px' },
        '7': { width: '28px' },
        '8': { width: '32px' },
        '9': { width: '36px' },
        '10': { width: '40px' },
        '11': { width: '44px' },
        '12': { width: '48px' },
        '14': { width: '56px' },
        '16': { width: '64px' },
        '20': { width: '80px' },
        '24': { width: '96px' },
        '28': { width: '112px' },
        '32': { width: '128px' },
        '36': { width: '144px' },
        '40': { width: '160px' },
        '44': { width: '176px' },
        '48': { width: '192px' },
        '52': { width: '208px' },
        '56': { width: '224px' },
        '60': { width: '240px' },
        '64': { width: '256px' },
        '72': { width: '288px' },
        '80': { width: '320px' },
        '96': { width: '384px' },
        'auto': { width: 'auto' },
        '1/2': { width: '50%' },
        '1/3': { width: '33.333333%' },
        '2/3': { width: '66.666667%' },
        '1/4': { width: '25%' },
        '2/4': { width: '50%' },
        '3/4': { width: '75%' },
        '1/5': { width: '20%' },
        '2/5': { width: '40%' },
        '3/5': { width: '60%' },
        '4/5': { width: '80%' },
        '1/6': { width: '16.666667%' },
        '2/6': { width: '33.333333%' },
        '3/6': { width: '50%' },
        '4/6': { width: '66.666667%' },
        '5/6': { width: '83.333333%' },
        '1/12': { width: '8.333333%' },
        '2/12': { width: '16.666667%' },
        '3/12': { width: '25%' },
        '4/12': { width: '33.333333%' },
        '5/12': { width: '41.666667%' },
        '6/12': { width: '50%' },
        '7/12': { width: '58.333333%' },
        '8/12': { width: '66.666667%' },
        '9/12': { width: '75%' },
        '10/12': { width: '83.333333%' },
        '11/12': { width: '91.666667%' },
        'full': { width: '100%' },
        'screen': { width: '100vw' },
        'min': { width: 'min-content' },
        'max': { width: 'max-content' },
        'fit': { width: 'fit-content' }
    },

    // ==================== HEIGHT ====================
    h: {
        '0': { height: '0' },
        'px': { height: '1px' },
        '0.5': { height: '2px' },
        '1': { height: '4px' },
        '1.5': { height: '6px' },
        '2': { height: '8px' },
        '2.5': { height: '10px' },
        '3': { height: '12px' },
        '3.5': { height: '14px' },
        '4': { height: '16px' },
        '5': { height: '20px' },
        '6': { height: '24px' },
        '7': { height: '28px' },
        '8': { height: '32px' },
        '9': { height: '36px' },
        '10': { height: '40px' },
        '11': { height: '44px' },
        '12': { height: '48px' },
        '14': { height: '56px' },
        '16': { height: '64px' },
        '20': { height: '80px' },
        '24': { height: '96px' },
        '28': { height: '112px' },
        '32': { height: '128px' },
        '36': { height: '144px' },
        '40': { height: '160px' },
        '44': { height: '176px' },
        '48': { height: '192px' },
        '52': { height: '208px' },
        '56': { height: '224px' },
        '60': { height: '240px' },
        '64': { height: '256px' },
        '72': { height: '288px' },
        '80': { height: '320px' },
        '96': { height: '384px' },
        'auto': { height: 'auto' },
        '1/2': { height: '50%' },
        '1/3': { height: '33.333333%' },
        '2/3': { height: '66.666667%' },
        '1/4': { height: '25%' },
        '2/4': { height: '50%' },
        '3/4': { height: '75%' },
        'full': { height: '100%' },
        'screen': { height: '100vh' },
        'min': { height: 'min-content' },
        'max': { height: 'max-content' },
        'fit': { height: 'fit-content' }
    },

    // ==================== POSITION ====================
    position: {
        'static': { position: 'static' },
        'fixed': { position: 'fixed' },
        'absolute': { position: 'absolute' },
        'relative': { position: 'relative' },
        'sticky': { position: 'sticky' }
    },

    // ==================== Z-INDEX ====================
    z: {
        '0': { zIndex: '0' },
        '10': { zIndex: '10' },
        '20': { zIndex: '20' },
        '30': { zIndex: '30' },
        '40': { zIndex: '40' },
        '50': { zIndex: '50' },
        'auto': { zIndex: 'auto' }
    },

    // ==================== OVERFLOW ====================
    overflow: {
        'auto': { overflow: 'auto' },
        'hidden': { overflow: 'hidden' },
        'visible': { overflow: 'visible' },
        'scroll': { overflow: 'scroll' },
        'x-auto': { overflowX: 'auto' },
        'y-auto': { overflowY: 'auto' },
        'x-hidden': { overflowX: 'hidden' },
        'y-hidden': { overflowY: 'hidden' },
        'x-scroll': { overflowX: 'scroll' },
        'y-scroll': { overflowY: 'scroll' },
        'x-visible': { overflowX: 'visible' },
        'y-visible': { overflowY: 'visible' }
    },

    // ==================== CURSOR ====================
    cursor: {
        'auto': { cursor: 'auto' },
        'default': { cursor: 'default' },
        'pointer': { cursor: 'pointer' },
        'wait': { cursor: 'wait' },
        'text': { cursor: 'text' },
        'move': { cursor: 'move' },
        'help': { cursor: 'help' },
        'not-allowed': { cursor: 'not-allowed' },
        'grab': { cursor: 'grab' },
        'grabbing': { cursor: 'grabbing' },
        'crosshair': { cursor: 'crosshair' },
        'zoom-in': { cursor: 'zoom-in' },
        'zoom-out': { cursor: 'zoom-out' }
    },

    // ==================== TRANSITION ====================
    transition: {
        'none': { transitionProperty: 'none' },
        'all': { transitionProperty: 'all', transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)', transitionDuration: '150ms' },
        'colors': { transitionProperty: 'color, background-color, border-color, text-decoration-color, fill, stroke', transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)', transitionDuration: '150ms' },
        'opacity': { transitionProperty: 'opacity', transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)', transitionDuration: '150ms' },
        'shadow': { transitionProperty: 'box-shadow', transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)', transitionDuration: '150ms' },
        'transform': { transitionProperty: 'transform', transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)', transitionDuration: '150ms' },
        
        'duration-75': { transitionDuration: '75ms' },
        'duration-100': { transitionDuration: '100ms' },
        'duration-150': { transitionDuration: '150ms' },
        'duration-200': { transitionDuration: '200ms' },
        'duration-300': { transitionDuration: '300ms' },
        'duration-500': { transitionDuration: '500ms' },
        'duration-700': { transitionDuration: '700ms' },
        'duration-1000': { transitionDuration: '1000ms' },
        
        'delay-75': { transitionDelay: '75ms' },
        'delay-100': { transitionDelay: '100ms' },
        'delay-150': { transitionDelay: '150ms' },
        'delay-200': { transitionDelay: '200ms' },
        'delay-300': { transitionDelay: '300ms' },
        'delay-500': { transitionDelay: '500ms' },
        'delay-700': { transitionDelay: '700ms' },
        'delay-1000': { transitionDelay: '1000ms' },
        
        'ease-linear': { transitionTimingFunction: 'linear' },
        'ease-in': { transitionTimingFunction: 'cubic-bezier(0.4, 0, 1, 1)' },
        'ease-out': { transitionTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)' },
        'ease-in-out': { transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)' }
    },

    // ==================== TRANSFORM ====================
    transform: {
        '': { transform: 'translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))' },
        'none': { transform: 'none' },
        
        'scale-0': { transform: 'scale(0)' },
        'scale-50': { transform: 'scale(0.5)' },
        'scale-75': { transform: 'scale(0.75)' },
        'scale-90': { transform: 'scale(0.9)' },
        'scale-95': { transform: 'scale(0.95)' },
        'scale-100': { transform: 'scale(1)' },
        'scale-105': { transform: 'scale(1.05)' },
        'scale-110': { transform: 'scale(1.1)' },
        'scale-125': { transform: 'scale(1.25)' },
        'scale-150': { transform: 'scale(1.5)' },
        
        'rotate-0': { transform: 'rotate(0deg)' },
        'rotate-45': { transform: 'rotate(45deg)' },
        'rotate-90': { transform: 'rotate(90deg)' },
        'rotate-180': { transform: 'rotate(180deg)' },
        'rotate-270': { transform: 'rotate(270deg)' },
        
        'translate-x-0': { transform: 'translateX(0)' },
        'translate-x-1': { transform: 'translateX(4px)' },
        'translate-x-2': { transform: 'translateX(8px)' },
        'translate-x-3': { transform: 'translateX(12px)' },
        'translate-x-4': { transform: 'translateX(16px)' },
        'translate-x-5': { transform: 'translateX(20px)' },
        'translate-x-full': { transform: 'translateX(100%)' },
        
        'translate-y-0': { transform: 'translateY(0)' },
        'translate-y-1': { transform: 'translateY(4px)' },
        'translate-y-2': { transform: 'translateY(8px)' },
        'translate-y-3': { transform: 'translateY(12px)' },
        'translate-y-4': { transform: 'translateY(16px)' },
        'translate-y-5': { transform: 'translateY(20px)' },
        'translate-y-full': { transform: 'translateY(100%)' }
    },

    // ==================== ANIMATION ====================
    animation: {
        'none': { animation: 'none' },
        'spin': { animation: 'spin 1s linear infinite' },
        'ping': { animation: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite' },
        'pulse': { animation: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite' },
        'bounce': { animation: 'bounce 1s infinite' },
        'fade-in': { animation: 'fadeIn 0.5s ease-out' },
        'fade-out': { animation: 'fadeOut 0.5s ease-in' },
        'slide-in': { animation: 'slideIn 0.3s ease-out' },
        'slide-out': { animation: 'slideOut 0.3s ease-in' }
    },

    // ==================== BACKGROUND UTILITIES ====================
    background: {
        'cover': { backgroundSize: 'cover' },
        'contain': { backgroundSize: 'contain' },
        'auto': { backgroundSize: 'auto' },
        'center': { backgroundPosition: 'center' },
        'top': { backgroundPosition: 'top' },
        'bottom': { backgroundPosition: 'bottom' },
        'left': { backgroundPosition: 'left' },
        'right': { backgroundPosition: 'right' },
        'repeat': { backgroundRepeat: 'repeat' },
        'no-repeat': { backgroundRepeat: 'no-repeat' },
        'repeat-x': { backgroundRepeat: 'repeat-x' },
        'repeat-y': { backgroundRepeat: 'repeat-y' }
    },

    // ==================== DISPLAY ====================
    display: {
        'block': { display: 'block' },
        'inline-block': { display: 'inline-block' },
        'inline': { display: 'inline' },
        'flex': { display: 'flex' },
        'inline-flex': { display: 'inline-flex' },
        'grid': { display: 'grid' },
        'inline-grid': { display: 'inline-grid' },
        'hidden': { display: 'none' }
    },

    // ==================== VISIBILITY ====================
    visibility: {
        'visible': { visibility: 'visible' },
        'invisible': { visibility: 'hidden' },
        'collapse': { visibility: 'collapse' }
    },

    // ==================== USER SELECT ====================
    select: {
        'none': { userSelect: 'none' },
        'text': { userSelect: 'text' },
        'all': { userSelect: 'all' },
        'auto': { userSelect: 'auto' }
    },

    // ==================== POINTER EVENTS ====================
    pointer: {
        'none': { pointerEvents: 'none' },
        'auto': { pointerEvents: 'auto' }
    },

    // ==================== RESIZE ====================
    resize: {
        'none': { resize: 'none' },
        'y': { resize: 'vertical' },
        'x': { resize: 'horizontal' },
        'both': { resize: 'both' }
    },

    // ==================== LIST STYLE ====================
    list: {
        'none': { listStyleType: 'none' },
        'disc': { listStyleType: 'disc' },
        'decimal': { listStyleType: 'decimal' },
        'circle': { listStyleType: 'circle' },
        'square': { listStyleType: 'square' },
        'roman': { listStyleType: 'upper-roman' }
    },

    // ==================== OBJECT FIT ====================
    object: {
        'contain': { objectFit: 'contain' },
        'cover': { objectFit: 'cover' },
        'fill': { objectFit: 'fill' },
        'none': { objectFit: 'none' },
        'scale-down': { objectFit: 'scale-down' }
    }
};

// ==================== KEYFRAMES ====================
export const ChaiKeyframes = {
    '@keyframes spin': {
        from: { transform: 'rotate(0deg)' },
        to: { transform: 'rotate(360deg)' }
    },
    '@keyframes ping': {
        '75%, 100%': { transform: 'scale(2)', opacity: '0' }
    },
    '@keyframes pulse': {
        '0%, 100%': { opacity: '1' },
        '50%': { opacity: '.5' }
    },
    '@keyframes bounce': {
        '0%, 100%': {
            transform: 'translateY(-25%)',
            animationTimingFunction: 'cubic-bezier(0.8, 0, 1, 1)'
        },
        '50%': {
            transform: 'translateY(0)',
            animationTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)'
        }
    },
    '@keyframes fadeIn': {
        from: { opacity: '0' },
        to: { opacity: '1' }
    },
    '@keyframes fadeOut': {
        from: { opacity: '1' },
        to: { opacity: '0' }
    },
    '@keyframes slideIn': {
        from: { transform: 'translateX(-100%)' },
        to: { transform: 'translateX(0)' }
    },
    '@keyframes slideOut': {
        from: { transform: 'translateX(0)' },
        to: { transform: 'translateX(-100%)' }
    }
};